# config.yaml

admin:
  port: ":80"
  max_photo_size: 32 # Mb
  photo_form_key: "photo"
  message_form_key: "message"
  faq_command_name: "FAQ"

tasks:
#  photo_path_goals:
  photo_path_tasks: "./images/tasks.jpg"
  photo_path_todos: "./images/todos.jpg"
  bar_count: 10

calendar:
  url: "http://localhost:8000/calendar"