# config.yaml

admin:
  port: ":80"
  max_photo_size: 32 # Mb
  photo_form_key: "photo"
  message_form_key: "message"

feedback:
  form: "https://best-company.com/feedback"
  duration: 2 # weeks
  photo_path: "./images/feedback.jpg"

notifications:
  photo_path :  "./images/notification.jpg"

  training_repeat:      2 # weeks
  training_day_of_week: "Fri" # day of the week
  training_hour:       17 # hour

  hr_meetup_repeat:     2 # weeks
  hr_meetup_day_of_week: "Fri" # day of the week
  hr_meetup_hour:      17 # hour

  mentor_meetup_repeat: 2 # weeks
  mentor_meetup_day_of_week: "Fri" # day of the week
  mentor_meetup_hour:  17 # hour

tasks:
#  photo_path_goals:
  photo_path_tasks: "./images/tasks.jpg"
  photo_path_todos: "./images/todos.jpg"
  bar_count: 10