version: "3.9"

services:
  postgres:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - storage:/var/lib/pgsql/data

volumes:
  storage: